# This file contains your private key.
# Do not give it away lightly!
Suite = "Ed25519"
Public = "d1821c3636bf0ea9bcf5574e243318672e92b4df5cabd4cbc95fa0ec2c461df7"
Private = "ec87eb222069771314e3dc47cebcb6802df33a7859cf0a630ac88e95f456f10e"
Address = "tls://127.0.0.1:7200"
ListenAddress = ""
Description = "co3"
WebSocketTLSCertificate = ""
WebSocketTLSCertificateKey = ""
