language: go

install:
  - go get -t ./...
  - go get github.com/dedis/Coding || true

before_install:
  - cd $TRAVIS_BUILD_DIR

script:
  - make test_fmt test_lint test_goveralls
  - cd external/java
  - mvn test

notifications:
  email: false

