// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        (unknown)
// source: initial.proto

package initial

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PkAndId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pk []byte `protobuf:"bytes,1,opt,name=pk,proto3" json:"pk,omitempty"`
	Id int32  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *PkAndId) Reset() {
	*x = PkAndId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_initial_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PkAndId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PkAndId) ProtoMessage() {}

func (x *PkAndId) ProtoReflect() protoreflect.Message {
	mi := &file_initial_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PkAndId.ProtoReflect.Descriptor instead.
func (*PkAndId) Descriptor() ([]byte, []int) {
	return file_initial_proto_rawDescGZIP(), []int{0}
}

func (x *PkAndId) GetPk() []byte {
	if x != nil {
		return x.Pk
	}
	return nil
}

func (x *PkAndId) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ProofMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Proof      []byte `protobuf:"bytes,1,opt,name=proof,proto3" json:"proof,omitempty"`
	Id         int32  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Ip         []byte `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`
	Randomness []byte `protobuf:"bytes,4,opt,name=randomness,proto3" json:"randomness,omitempty"`
}

func (x *ProofMsg) Reset() {
	*x = ProofMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_initial_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProofMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProofMsg) ProtoMessage() {}

func (x *ProofMsg) ProtoReflect() protoreflect.Message {
	mi := &file_initial_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProofMsg.ProtoReflect.Descriptor instead.
func (*ProofMsg) Descriptor() ([]byte, []int) {
	return file_initial_proto_rawDescGZIP(), []int{1}
}

func (x *ProofMsg) GetProof() []byte {
	if x != nil {
		return x.Proof
	}
	return nil
}

func (x *ProofMsg) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProofMsg) GetIp() []byte {
	if x != nil {
		return x.Ip
	}
	return nil
}

func (x *ProofMsg) GetRandomness() []byte {
	if x != nil {
		return x.Randomness
	}
	return nil
}

var File_initial_proto protoreflect.FileDescriptor

var file_initial_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x22, 0x29, 0x0a, 0x07, 0x50, 0x6b, 0x41, 0x6e,
	0x64, 0x49, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x70, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x02, 0x70, 0x6b, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x02, 0x69, 0x64, 0x22, 0x60, 0x0a, 0x08, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x4d, 0x73, 0x67, 0x12,
	0x14, 0x0a, 0x05, 0x70, 0x72, 0x6f, 0x6f, 0x66, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05,
	0x70, 0x72, 0x6f, 0x6f, 0x66, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x02, 0x69, 0x70, 0x12, 0x1e, 0x0a, 0x0a, 0x72, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x6e,
	0x65, 0x73, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x72, 0x61, 0x6e, 0x64, 0x6f,
	0x6d, 0x6e, 0x65, 0x73, 0x73, 0x32, 0x75, 0x0a, 0x08, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x41, 0x6c,
	0x6c, 0x12, 0x31, 0x0a, 0x07, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x50, 0x4b, 0x12, 0x10, 0x2e, 0x69,
	0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x2e, 0x50, 0x6b, 0x41, 0x6e, 0x64, 0x49, 0x64, 0x1a, 0x10,
	0x2e, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x2e, 0x50, 0x6b, 0x41, 0x6e, 0x64, 0x49, 0x64,
	0x22, 0x00, 0x30, 0x01, 0x12, 0x36, 0x0a, 0x0a, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x50, 0x72, 0x6f,
	0x6f, 0x66, 0x12, 0x11, 0x2e, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x2e, 0x50, 0x72, 0x6f,
	0x6f, 0x66, 0x4d, 0x73, 0x67, 0x1a, 0x11, 0x2e, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x2e,
	0x50, 0x72, 0x6f, 0x6f, 0x66, 0x4d, 0x73, 0x67, 0x22, 0x00, 0x30, 0x01, 0x42, 0x0c, 0x5a, 0x0a,
	0x2e, 0x2f, 0x3b, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_initial_proto_rawDescOnce sync.Once
	file_initial_proto_rawDescData = file_initial_proto_rawDesc
)

func file_initial_proto_rawDescGZIP() []byte {
	file_initial_proto_rawDescOnce.Do(func() {
		file_initial_proto_rawDescData = protoimpl.X.CompressGZIP(file_initial_proto_rawDescData)
	})
	return file_initial_proto_rawDescData
}

var file_initial_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_initial_proto_goTypes = []interface{}{
	(*PkAndId)(nil),  // 0: initial.PkAndId
	(*ProofMsg)(nil), // 1: initial.ProofMsg
}
var file_initial_proto_depIdxs = []int32{
	0, // 0: initial.BroadAll.BroadPK:input_type -> initial.PkAndId
	1, // 1: initial.BroadAll.BroadProof:input_type -> initial.ProofMsg
	0, // 2: initial.BroadAll.BroadPK:output_type -> initial.PkAndId
	1, // 3: initial.BroadAll.BroadProof:output_type -> initial.ProofMsg
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_initial_proto_init() }
func file_initial_proto_init() {
	if File_initial_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_initial_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PkAndId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_initial_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProofMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_initial_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_initial_proto_goTypes,
		DependencyIndexes: file_initial_proto_depIdxs,
		MessageInfos:      file_initial_proto_msgTypes,
	}.Build()
	File_initial_proto = out.File
	file_initial_proto_rawDesc = nil
	file_initial_proto_goTypes = nil
	file_initial_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// BroadAllClient is the client API for BroadAll service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BroadAllClient interface {
	BroadPK(ctx context.Context, in *PkAndId, opts ...grpc.CallOption) (BroadAll_BroadPKClient, error)
	BroadProof(ctx context.Context, in *ProofMsg, opts ...grpc.CallOption) (BroadAll_BroadProofClient, error)
}

type broadAllClient struct {
	cc grpc.ClientConnInterface
}

func NewBroadAllClient(cc grpc.ClientConnInterface) BroadAllClient {
	return &broadAllClient{cc}
}

func (c *broadAllClient) BroadPK(ctx context.Context, in *PkAndId, opts ...grpc.CallOption) (BroadAll_BroadPKClient, error) {
	stream, err := c.cc.NewStream(ctx, &_BroadAll_serviceDesc.Streams[0], "/initial.BroadAll/BroadPK", opts...)
	if err != nil {
		return nil, err
	}
	x := &broadAllBroadPKClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type BroadAll_BroadPKClient interface {
	Recv() (*PkAndId, error)
	grpc.ClientStream
}

type broadAllBroadPKClient struct {
	grpc.ClientStream
}

func (x *broadAllBroadPKClient) Recv() (*PkAndId, error) {
	m := new(PkAndId)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *broadAllClient) BroadProof(ctx context.Context, in *ProofMsg, opts ...grpc.CallOption) (BroadAll_BroadProofClient, error) {
	stream, err := c.cc.NewStream(ctx, &_BroadAll_serviceDesc.Streams[1], "/initial.BroadAll/BroadProof", opts...)
	if err != nil {
		return nil, err
	}
	x := &broadAllBroadProofClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type BroadAll_BroadProofClient interface {
	Recv() (*ProofMsg, error)
	grpc.ClientStream
}

type broadAllBroadProofClient struct {
	grpc.ClientStream
}

func (x *broadAllBroadProofClient) Recv() (*ProofMsg, error) {
	m := new(ProofMsg)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// BroadAllServer is the server API for BroadAll service.
type BroadAllServer interface {
	BroadPK(*PkAndId, BroadAll_BroadPKServer) error
	BroadProof(*ProofMsg, BroadAll_BroadProofServer) error
}

// UnimplementedBroadAllServer can be embedded to have forward compatible implementations.
type UnimplementedBroadAllServer struct {
}

func (*UnimplementedBroadAllServer) BroadPK(*PkAndId, BroadAll_BroadPKServer) error {
	return status.Errorf(codes.Unimplemented, "method BroadPK not implemented")
}
func (*UnimplementedBroadAllServer) BroadProof(*ProofMsg, BroadAll_BroadProofServer) error {
	return status.Errorf(codes.Unimplemented, "method BroadProof not implemented")
}

func RegisterBroadAllServer(s *grpc.Server, srv BroadAllServer) {
	s.RegisterService(&_BroadAll_serviceDesc, srv)
}

func _BroadAll_BroadPK_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PkAndId)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BroadAllServer).BroadPK(m, &broadAllBroadPKServer{stream})
}

type BroadAll_BroadPKServer interface {
	Send(*PkAndId) error
	grpc.ServerStream
}

type broadAllBroadPKServer struct {
	grpc.ServerStream
}

func (x *broadAllBroadPKServer) Send(m *PkAndId) error {
	return x.ServerStream.SendMsg(m)
}

func _BroadAll_BroadProof_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ProofMsg)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BroadAllServer).BroadProof(m, &broadAllBroadProofServer{stream})
}

type BroadAll_BroadProofServer interface {
	Send(*ProofMsg) error
	grpc.ServerStream
}

type broadAllBroadProofServer struct {
	grpc.ServerStream
}

func (x *broadAllBroadProofServer) Send(m *ProofMsg) error {
	return x.ServerStream.SendMsg(m)
}

var _BroadAll_serviceDesc = grpc.ServiceDesc{
	ServiceName: "initial.BroadAll",
	HandlerType: (*BroadAllServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "BroadPK",
			Handler:       _BroadAll_BroadPK_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "BroadProof",
			Handler:       _BroadAll_BroadProof_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "initial.proto",
}
