# This file contains your private key.
# Do not give it away lightly!
Suite = "Ed25519"
Public = "c56ba7340d9c65c28fb9c3e1e41db1b33fcac99e10185cbf049e5dd02cae620a"
Private = "7f64f69d5beea9fc9d937850f6dad25e6bbac2ecc945758823743ffd784a730d"
Address = "tls://127.0.0.1:7100"
ListenAddress = ""
Description = "co2"
WebSocketTLSCertificate = ""
WebSocketTLSCertificateKey = ""
